language: php

php:
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require "skimia/foundation" dev-master
  - composer require "satooshi/php-coveralls" dev-master
  - composer update
  - cd ./vendor/skimia/foundation

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php ../../bin/coveralls -v -c vendor/skimia/foundation/.coveralls.yml
