language: php
sudo: false
php:
- 5.6
- 7
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_install:
- composer self-update
- composer create-project laravel/laravel laravel 5.1
- cd ./laravel
- composer require "skimia/foundation" dev-master
- cd ./vendor/skimia/foundation
script:
- phpunit --coverage-clover=coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
- if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST
  = 'false' ]; then sh generate-api.sh; fi
env:
  global:
  - GIT_NAME: "'Skimia Foundation'"
  - GIT_EMAIL: kessler.dev@gmail.com
  - GH_REF: github.com/skimia/foundation
  - secure: E4UbRsbxVvlgYazU2Um2xpHLydPKkqmXBTeHWiEcD9/uRr/3kWCmb7+9D+UMH1p6nnXcMftzsAg2GOXuJdQaKp6UPo+oBGNQCtnajRQSsh9hZhh3r0UBkLH7NVT7CTjpHSQrG3iZUabH7vuw5dt/zTASynH9JE8r5SL1gA4sXVtBtlF6w8rR6Y76FSrCxYG9XZS/Y5L8VBElCTyooYYPQHv0T1Yvs7HwSK2Zya8WtMwyQE93FikCnaGW/1uB9z+M/533eF0/bHNhZBMRhqMCvECbtsZ29oehzWTiV/1yVwZ8x3/+/pwhjbTHf1gV9GcLFPClCF33KhAf3t3gCwybN+LIvIqiwtS5x3mlGNZDbpyiN/dkNpHz615Br/G8bldO4wujqQyWl0fkBg8vNKD0JG7IT7pXskUkpwQDcxQOvysxO612xw98WCBYE72w1d5guGl+OJByCRTgkX70PM6q+TLrlFzZ2dVLBT7UDn5G+2sae6PzGcoOU8XZeXb3jkBRSc8Xq2gCOo5npWk0GVo45z2uo0lzjDvgMz/TFRouJ33blAsESXhJZTyly4AeVzdJIO2k56EeeBrjxXMQ8RJM3HNhl1ZfN05JJQTmagW2jNja4BzoQ+Ak8X0nHjFyL+uc4MhoJk37ImiJL/gxu1D3c832cVTEUXUNiHVdSmHq8x0=
  - secure: noDY6YN3TTGtZ+RoAnbvnDq4zCQJqDq5SCLhXvNG4HrN0zX21YiAy3tRHZla83yegxfNnPKV82py1SQfpEuskZuHuRCcQWPgaP28W638l8b+yHKHfDoAtC8keVjBLNYgdTjOy/FtJR4owrE4lcNA9ao3x2Az8fd+OkSEsLvjjCTT4ykR53/BWqQfQ+p7uzPK33cXTjur3AqXTrkyEnaLVuYnNfAGSRqNJbgLlZryGfyZf/qCyo7+yhADwnJDYfevCdCl8t7csF2vtBy5JzDKBWkVgX4Y9ROHlcbilBWs0NnewkEXcrhPRxtQTXGEBKs60y7hD0MD8JvEtSGe+vWlakCetP1HRCCnCNbkbFYo+xs4ZiP0pbSQ7dKeYkeiuF2sNV9s5vb+FqcGFZeQXxXxTocoOwbah1quRDRJLt41O5hpTvcp23HTOJ6TtDHzrkcWhpy00kZuVYhn5IBTx4bRRXGyrAFLnASVGDy1IFQrmIMrDXIwLKmlKYEAKOH0HPfuFDW8ogA3zaz4piJ+qENbsdyNrTX5wzAMWvRIb8AGHku7fhyNfJv/IoPJNX9p9gq3qZ7VPl0r6OvDqN6GzRd5xPvxQMNKXT7jYk1SfeAv3Ezh00Q2eceX7iuoi4UKTlg2+JuvvT4gQqU2Pw2L7gWZEdBQcukvI9bk2Ui/F3rKjlE=
