language: php

php:
  - 5.6
  - 5.7
  - 7
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - pip install --user codecov
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require "skimia/foundation" dev-master
  - cd ./vendor/skimia/foundation

script:
  - phpunit --coverage-clover=coverage.xml
  - ls

after_success:
  - bash <(curl -s https://codecov.io/bash)
